common: &local_settings
  storage: :filesystem
  url: "/system/:class/:attachment/:id_partition/:normalized_basename_:style.:extension"
  # command_path: /usr/bin

s3_amazon: &s3_settings
  <<: *local_settings
  storage: :s3
  path: ":class/:attachment/:id_partition/:normalized_basename_:style.:extension"
  url: ":s3_domain_url"

development:
  <<: *local_settings

staging:
  <<: *local_settings

production:
  <<: *s3_settings
  bucket: holidaysreminder